<Manager>:
    transition: NoTransition()
    current: "home"
    Login:
    SignUp:
    Home:
#    PictureManager:
#        id: picture
    ProductLookOut:
        id: lookout
    Setting:
        id:setting
    Category:
        id: category
#    Accommodation:
#        id: acco
    Notification:
        id: notify
    CustomerCare:
        id: customer
    Order:
        id: order
    Review:
        id: review
    Deals:
        id: deals
    StudentInfo:
        id: s_zone